version: "3"

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    
